### ISSUE TITLE
Matching Order

### ISSUE THREAD

**Issue by rihp** [dOrgTech/rarible-sdk#6] opened 2021-05-31 16:51 UTC

**Comment by rihp** [comment] 2021-06-03 11:29
@benefacto according to our last call, i'm understanding that alex has relied this design decision, we should have a quick call internally to sort this out, but my initial thought is that this can be abstracted away from the user

**Comment by benefacto** [comment] 2021-06-07 17:23
Duplicate of #4

**Closed by benefacto** 2021-06-07 17:23 UTC
